//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventParticipant
    {
        public int ParticipantId { get; set; }
        public int EventId { get; set; }
        public int UserId { get; set; }
        public System.DateTime JoinedAt { get; set; }
    
        public virtual PlantationEvent PlantationEvent { get; set; }
        public virtual User User { get; set; }
    }
}
