//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public Issue()
        {
            this.tasks = new HashSet<task>();
        }
    
        public int IssueId { get; set; }
        public int UserId { get; set; }
        public string IssueType { get; set; }
        public string Discription { get; set; }
        public string Location { get; set; }
        public string Image { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
