//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenANewEntities : DbContext
    {
        public GreenANewEntities()
            : base("name=GreenANewEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EventParticipant> EventParticipants { get; set; }
        public DbSet<Issue> Issues { get; set; }
        public DbSet<PlantationEvent> PlantationEvents { get; set; }
        public DbSet<task> tasks { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
