//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlantationEvent
    {
        public PlantationEvent()
        {
            this.EventParticipants = new HashSet<EventParticipant>();
        }
    
        public int EventId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public System.DateTime EventDate { get; set; }
        public int CreatedBy { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<EventParticipant> EventParticipants { get; set; }
        public virtual User User { get; set; }
    }
}
