//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int TaskId { get; set; }
        public int IssueId { get; set; }
        public int AssignedTo { get; set; }
        public string TaskType { get; set; }
        public System.DateTime Deadline { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public string CompletionImage { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual User User { get; set; }
    }
}
