//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenANew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.EventParticipants = new HashSet<EventParticipant>();
            this.Issues = new HashSet<Issue>();
            this.PlantationEvents = new HashSet<PlantationEvent>();
            this.tasks = new HashSet<task>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<EventParticipant> EventParticipants { get; set; }
        public virtual ICollection<Issue> Issues { get; set; }
        public virtual ICollection<PlantationEvent> PlantationEvents { get; set; }
        public virtual ICollection<task> tasks { get; set; }
    }
}
